# Generated by Django 5.0.9 on 2024-09-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Кузов')),
            ],
            options={
                'verbose_name': 'Кузов',
                'verbose_name_plural': 'Кузов',
                'db_table': 'carcase',
            },
        ),
    ]
