# Generated by Django 5.0.9 on 2024-09-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carcases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcase',
            name='brand_auto',
        ),
    ]
