# Generated by Django 5.0.9 on 2024-09-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voltage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voltage',
            options={'verbose_name': 'Напряжение', 'verbose_name_plural': 'Напряжение'},
        ),
    ]
