# Generated by Django 5.0.9 on 2024-09-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LampBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Цоколь')),
                ('watts', models.CharField(max_length=10, verbose_name='Мощность')),
            ],
        ),
    ]
