# Generated by Django 5.0.9 on 2024-09-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carcases', '0001_initial'),
        ('lamp_types', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LampBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Цоколь')),
                ('slug', models.SlugField(blank=True, default='')),
                ('watts', models.CharField(blank=True, max_length=10, null=True, verbose_name='Мощность')),
                ('image', models.ImageField(default='no_image.svg', upload_to='lamp_bases', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Цоколь',
                'verbose_name_plural': 'Цоколь',
                'db_table': 'lamp_base',
            },
        ),
        migrations.CreateModel(
            name='PlaceLamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcases.carcase')),
                ('lamp_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='lamp_bases.lampbase')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
                ('type', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='lamp_types.type')),
            ],
        ),
    ]
