# Generated by Django 5.0.9 on 2024-09-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamp_bases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lampbase',
            options={'verbose_name': 'Цоколь', 'verbose_name_plural': 'Цоколь'},
        ),
        migrations.AlterModelTable(
            name='lampbase',
            table='lamp_base',
        ),
    ]
