# Generated by Django 5.0.9 on 2024-09-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamp_bases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placelamp',
            name='type',
        ),
    ]
