# Generated by Django 5.0.9 on 2024-09-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp_bases', '0002_remove_placelamp_type'),
        ('lamp_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placelamp',
            name='type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='lamp_types.type'),
        ),
    ]
