# Generated by Django 5.0.9 on 2024-09-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp_bases', '0002_alter_lampbase_options_alter_lampbase_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampbase',
            name='watts',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Мощность'),
        ),
    ]
