# Generated by Django 5.0.9 on 2024-10-01 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp_bases', '0004_alter_placelamp_lamp_base'),
        ('lamp_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampbase',
            name='type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='lamp_types.type'),
        ),
        migrations.AlterField(
            model_name='placelamp',
            name='lamp_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='lamp_bases.lampbase'),
        ),
    ]
