# Generated by Django 5.0.9 on 2024-09-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Марку автомобилей',
                'verbose_name_plural': 'Марки автомобилей',
                'db_table': 'brand_auto',
            },
        ),
    ]
