# Generated by Django 5.0.9 on 2024-09-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_autos', '0002_brandauto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandauto',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
