# Generated by Django 5.0.9 on 2024-09-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_autos', '0003_alter_brandauto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandauto',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
