# Generated by Django 5.0.9 on 2024-09-27 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp_types', '0002_type_slug'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='places.place')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamp_types.type')),
            ],
        ),
    ]
