# Generated by Django 5.0.9 on 2024-09-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='no_image.svg', upload_to='profiles', verbose_name='Изображение'),
        ),
    ]
