# Generated by Django 5.0.9 on 2024-09-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amount_types', '0001_initial'),
        ('brand_lamps', '0001_initial'),
        ('colors', '0001_initial'),
        ('lamp_bases', '0003_alter_lampbase_watts'),
        ('lamp_types', '0001_initial'),
        ('length', '0001_initial'),
        ('offset_lamps', '0001_initial'),
        ('voltage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('watts', models.CharField(blank=True, max_length=10, null=True, verbose_name='Мощность/Люмены')),
                ('price', models.IntegerField(default=0, null=True, verbose_name='Цена')),
                ('image', models.ImageField(default='no_image.svg', upload_to='profiles', verbose_name='Изображение')),
                ('amount_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='amount_types.amounttype', verbose_name='Тип количества')),
                ('base', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lamp_bases.lampbase', verbose_name='Цоколь')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='brand_lamps.brandlamp', verbose_name='Производитель')),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='colors.color', verbose_name='Цвет')),
                ('length', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='length.length', verbose_name='Длина')),
                ('offset', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='offset_lamps.offset', verbose_name='Смещение')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lamp_types.type', verbose_name='Тип лампы')),
                ('voltage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voltage.voltage', verbose_name='Напряжение')),
            ],
            options={
                'verbose_name': 'Лампу',
                'verbose_name_plural': 'Лампы',
                'db_table': 'lamp',
            },
        ),
    ]
