# Generated by Django 5.0.9 on 2024-10-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='in_cart',
            field=models.BooleanField(default=False, verbose_name='Добавлено в корзину?'),
        ),
    ]
