# Generated by Django 5.0.7 on 2024-09-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='image',
            field=models.ImageField(default='no_image.svg', upload_to='lamps_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Описание'),
        ),
    ]
