# Generated by Django 5.0.9 on 2024-09-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamps', '0002_alter_lamp_image_alter_lamp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='image',
            field=models.ImageField(default='no_image.svg', upload_to='profiles', verbose_name='Изображение'),
        ),
    ]
