# Generated by Django 5.0.9 on 2024-10-02 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
        ('lamps', '0004_lamp_slug'),
        ('length', '0001_initial'),
        ('offset_lamps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='color',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='colors.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='length',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='length.length', verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='offset',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='offset_lamps.offset', verbose_name='Смещение'),
        ),
    ]
