# Generated by Django 5.0.9 on 2024-09-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=10, verbose_name='Тип количества')),
            ],
            options={
                'verbose_name': 'Тип количества',
                'verbose_name_plural': 'Типы количества',
                'db_table': 'amount',
            },
        ),
    ]
