# Generated by Django 5.0.9 on 2024-09-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=10, verbose_name='Длина')),
            ],
            options={
                'verbose_name': 'Длина',
                'verbose_name_plural': 'Длина',
                'db_table': 'length',
            },
        ),
    ]
