# Generated by Django 5.0.9 on 2024-09-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='offset')),
            ],
            options={
                'verbose_name': 'Смещение',
                'verbose_name_plural': 'Смещения',
                'db_table': 'offset',
            },
        ),
    ]
