# Generated by Django 5.0.9 on 2024-09-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offset_lamps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offset',
            options={'verbose_name': 'Смещение', 'verbose_name_plural': 'Смещение'},
        ),
    ]
